services:

  # Context pane
  calista.context:
    class: MakinaCorpus\Drupal\Calista\Context\ContextPane
    arguments: ['@event_dispatcher', '@request_stack']

  # Action providers
  calista.action_provider.node:
    public: false
    class: MakinaCorpus\Drupal\Calista\Action\CoreNodeActionProvider
    tags: [{name: calista.action_provider}]

  # @todo Action processors are Drupal only per signature as of now
  calista.processor_registry:
    class: MakinaCorpus\Drupal\Calista\Action\ProcessorActionProvider
    tags: [{name: calista.action_provider}]

  # Property info extractors
  calista.property_info_extractor.entity:
    public: false
    class: MakinaCorpus\Drupal\Calista\PropertyInfo\EntityProperyInfoExtractor
    tags:
      - {name: property_info.list_extractor}
      - {name: property_info.type_extractor}
      - {name: property_info.description_extractor}
      - {name: property_info.access_extractor}

  # Drupal datasources
  calista.datasource.drupal_account:
    public: true
    class: MakinaCorpus\Drupal\Calista\Datasource\DefaultAccountDatasource
    arguments: ['@database', '@entity.manager']
    tags: [{name: calista.datasource}]
  calista.datasource.drupal_node:
    public: false
    class: MakinaCorpus\Drupal\Calista\Datasource\DefaultNodeDatasource
    arguments: ['@database', '@entity.manager']
    tags: [{name: calista.datasource, id: node}]

  # Sample Drupal page definition from services
  calista.page.drupal_account:
    public: true
    class: MakinaCorpus\Drupal\Calista\Page\AccountPageDefinition
    tags: [{name: calista.page_definition}]

  # Event subscribers
  calista.twig_view_event_subscriber:
    class: MakinaCorpus\Drupal\Calista\EventDispatcher\ViewEventSubscriber
    tags: [{name: event_subscriber}]

  # Portlet registry
  calista.portlet_registry:
    public: true
    class: MakinaCorpus\Drupal\Calista\Portlet\PortletRegistry
